serenity.project.name=SWAG LABS
serenity.test.root=open.example
webdriver.driver=chrome
webdriver.autodownload=true
webdriver.browser.maximized=true
serenity.use.unique.browser=false
serenity.restart.browser.each.scenario=true
chrome.switches=--headless,--disable-gpu
